### ISSUE TITLE
It should be possible to return 404 instead of rendered template based on responses from services

### ISSUE THREAD

**Issue by kacper-cognifide** [Knotx/knotx#392]
### Version used

* knot.x: 1.2.1

### Context of the issue/feature

It should be possible to return a 404 HTML status code instead of rendered template based on the responses from services.

Project case:
We have a template for rendering image and it's meta data based on the response from a microservice. When user loads a non-existing image we can check if the image exists in the template but we can only change the content of the output, for example rendering "Image not found" message. It would be better from user experience and SEO perspective to return 404 HTTP status code instead.

### Bug reproducer

* NA

### Steps to reproduce

NA

### Appendix

* Anything else that can be relevant

**Comment by szymonkrzysztyniak** [comment]
+1

**Comment by rkarwacki** [comment]
This would be very useful, we also have a need in the project for this exact feature. 

One possible solution is, if private method `createSuccessResponse` in `ServiceKnotProxyImpl` became protected, then it would be possible to override it from the project code and set custom response status based on some adapters response. 

The other solution would be to implement a feature in Service Knot to allow it to react to Signals, simillar to how Action Knot currently handles signals returned by Action Adapters.

**Comment by marcinczeczko** [comment]
Actually, it's a good idea. My proposal is as follows, please comment:
- In `ServiceKnotProxyImpl` rename `createSuccessResponse` into `createResponse` (as it's not necessarily success one), and `processError` into `createErrorResponse` (that will handle serious errors)
- a logic inside `createSuccessResponse` to be loaded by java `ServiceLoader` instead of being hardcoded in here
- existing logic extract into a separate class and register in java service loader
- same can be done for `createError` method

This way, we can expose SPI so any project can provide its own implementation without need to extend `ServiceKnotProxyImpl` class

**Comment by Skejven** [comment]
@kacper-cognifide 
This case is now covered thanks to [Fragment Processing](https://github.com/Knotx/knotx-fragments-handler), where you can model such behavior (when data service return `404`, you enforce `404` on the final response by emitting proper processing status).
You may check out [2.0.0-RC1](https://search.maven.org/search?q=g:io.knotx%20AND%20v:2.0.0-RC1) at the moment.
